config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :listings
  resources :carts, only: [:create, :index]
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can [:index, :show, :new, :create], Listing
    can [:edit, :update, :destroy], Listing, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :listings
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_listings
  has_many :listings, through: :cart_listings
  belongs_to :user
end

app/models/cart_listing.rb
class CartListing < ApplicationRecord
  belongs_to :listing
  belongs_to :cart
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :breed
  enum sex: { female: 0, male: 1 }
  has_one_attached :picture
  belongs_to :user
  validates :title, presence: true
  has_many :cart_listings
  has_many :carts, through: :cart_listings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    render file: "#{Rails.root}/public/403.html" , status: 403
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index 
    if user_signed_in? && current_user.carts.last
      @cart = current_user.carts.last.listings
      @listing_ids = @cart.map do |listing|
        listing.id
      end
    else
      redirect_to listings_path
    end 
  end 
  
  def create
    if current_user.carts.empty?
      cart = Cart.create(completed: false, user_id: current_user.id)
    else
      cart = current_user.carts.last
    end 
    listing = Listing.find(params[:listing_id])
    cart.listings << listing
    redirect_to listings_path
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @listings_sold = Listing.where(sold: true)
    @listings_unsold = Listing.where(sold: false)
    if !session[:count]  
      session[:count] = 1
    else
      session[:count] += 1
    end
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.create(listing_params)
    if @listing.errors.any?
      render :new
    else
      flash[:success] = "You successfully created a new listing!"
      redirect_to @listing
    end 
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing.id)
    else
      render :edit
    end 
  end

  def destroy
    @listing.destroy
    redirect_to root_path
  end

  private 

  def listing_params
    params.require(:listing).permit(:title, :description, :breed_id, :picture)
  end 

  def set_listing 
    @listing = Listing.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
  end

  def not_found 
  end 
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhook]

  def success 
    @listings = current_user.carts.last.listings
    Cart.create(completed: false, user_id: current_user.id)
  end 

  def webhook
    payment_id = params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_id)
    listing_ids = payment.metadata.listing_ids.split(",")
    listings = []
    listing_ids.each do |id|
      listing = Listing.find(id)
      listing.sold = true
      listing.save
    end 
    user = User.find(payment.metadata.user_id)
    cart = user.carts.last
    cart.completed = true
    cart.save
    # need to void the cart
    head 200
  end 

  def get_stripe_id
    @listings = current_user.carts.last.listings
    line_items = @listings.map do |listing|
      {
        name: listing.title,
        description: listing.description,
        amount: listing.deposit,
        currency: 'aud',
        quantity: 1,
      }
    end 
    listing_ids = @listings.pluck(:id).join(",")
    session_id = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user.email,
      line_items: line_items,
      payment_intent_data: {
        metadata: {
          user_id: current_user.id,
          listing_ids: listing_ids
        }
      },
      success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingIds=#{listing_ids}",
      cancel_url: "#{root_url}listings"
    ).id
    render :json => {id: session_id, stripe_public_key: Rails.application.credentials.dig(:stripe, :public_key)}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
  def background_image(listing)
    return "
      background: url(#{url_for(listing.picture)});
      height: 100%; 
      background-position: center; 
      background-size: cover;
    "
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/carts/index.html.erb
<h1>Cart</h1>

<ul>
  <% @cart.each do |listing| %>
    <li><%= listing.title %> | <%= number_to_currency(listing.deposit / 100.0) %></li>
  <% end %>
</ul>

<%= link_to "Pay Now 💵", "", id: "stripe" %>

<%= javascript_pack_tag "stripe" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snake Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "shared/nav" %>
      <%= notice %>
      <div class="container">
        <%= yield %>  
      </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= render "shared/form-errors", resource: listing %>

<%= form_with model: listing, local: true, class: "listings-form" do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= form.label :breeds %>
  <%= form.collection_select(:breed_id, Breed.all, :id, :name) %>
  <%= form.label :picture %> 
  <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  <%= form.submit %>
<% end %>

app/views/listings/_image-logic.html.erb
<% if listing.picture.attached? %>
  <div style="<%= background_image(listing) %>">
  </div>
<% else %>  
  <div class="backup-image"></div>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit a listing</h1>

<%= render "form", listing: @listing %>

app/views/listings/index.html.erb
<% if flash[:unauthorized] %>
  <p><%= flash[:unauthorized] %></p>
<% end %>

<div class="content">
  <h2>Unsold items</h2>
  <% @listings_unsold.each do |listing| %>
    <%= link_to listing_path(listing.id) do %>
      <div class="listing">
        <div class="listing-content">      
          <h3>Title: <%= listing.title %></h3>
          <p>Description: <%= listing.description %></p>
          <p>Breed: <%= listing.breed.name %></p>
        </div>
        <div class="listing-image">      
          <%= render "image-logic", listing: listing %>
        </div>
      </div>        
    <% end %>
  <% end %>
  <h2>Listings sold</h2>
  <% @listings_sold.each do |listing| %>
    <%= link_to listing_path(listing.id) do %>
      <div class="listing">
        <div class="listing-content">      
          <h3>Title: <%= listing.title %></h3>
          <p>Description: <%= listing.description %></p>
          <p>Breed: <%= listing.breed.name %></p>
        </div>
        <div class="listing-image">      
          <%= render "image-logic", listing: listing %>
        </div>
      </div>        
    <% end %>
  <% end %>
</div>

<h1>Page count</h1>
<h3><%= session[:count] %></h3>

app/views/listings/new.html.erb
<div class="content">
  <h1>Create a listing</h1>

  <%= render "form", listing: @listing %>
</div>

app/views/listings/show.html.erb
<% if flash[:success] %>
  <p><%= flash[:success] %></p>
<% end %>

<h1><%= @listing.title %></h1>
<p><%= @listing.description %></p>
<p>Price: <%= number_to_currency(@listing.deposit / 100.0) %></p>

<div class="show-image">  
  <%= render "image-logic", listing: @listing %>
</div>

<div class="show-edit-delete">
  <% if current_user && current_user.id == @listing.user_id %>
    <%= link_to "Edit", edit_listing_path(@listing.id) %>
    <%= link_to "Delete", listing_path(@listing.id), method: :delete %>
  <% end %>
  <% if user_signed_in? && @listing.sold == false && @listing.user.id != current_user.id %>
    <%= link_to "Add to cart", carts_path(listing_id: @listing.id), method: :post  %>
  <% end %>
  <%= link_to "Back", :back %>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="content">  
    <div class="hero">
      <%= image_tag "snake-hero.png", class: "snake-hero" %>
    </div>
    <div class="header">
      <h1>SnakeMarketplace</h1>
      <h3>Parseltongue speakers only 🧙‍♀️</h3>
      <div class="sign-up-button">
        <%= button_to "Sign up", new_user_registration_path, method: :get %>
      </div>
    </div>
  </div>
</div>

app/views/pages/not_found.html.erb
<h1 style="font-size: 100px">404 wrong route!!!! ❌</h1>

app/views/payments/success.html.erb
<div>
  <% @listings.each do |listing| %>
    <h1>You successfully purchased <%= listing.title %></h1> 
    <h3>You paid <%= number_to_currency(listing.deposit / 100) %></h3>
  <% end %>
</div>

app/views/shared/_form-errors.html.erb
<% if resource.errors.any? %>
  <div class="form-errors">
    <ul>  
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end  %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <%= link_to "🐍", root_path %>
  <%= link_to "Listings", listings_path %>
  <%= link_to "Create New Listing", new_listing_path %>
  <% if user_signed_in? %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <%= link_to "Cart", carts_path %>
  <% else %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</nav>